plugins:
  - jekyll-feed

collections:
  authors:
    output: true
  tags:
    output: true
    permalink: tag/:title/

name: "Apollo Tech Corner"

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title:output_ext
  - scope:
      path: ""
      type: tags
    values:
      layout: tag
  - scope:
      path: ""
    values:
      layout: "default"
