plugins:
  - jekyll-feed
  - jekyll-favicon

exclude:
  - "Dockerfile"
  - "docker-compose.yml"

collections:
  tags:
    output: true
    permalink: tag/:title/
  shows:
    output: true
    permalink: show/:title.html

name: "Apollo Tech Corner"
url: "https://apollofops.net"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /news/:categories/:title:output_ext
  - scope:
      path: ""
      type: tags
    values:
      layout: tag
  - scope:
      path: ""
      type: shows
    values:
      layout: show
  - scope:
      path: ""
    values:
      layout: "default"

feed:
  posts_limit: 1000

favicon:
  source: favicon.png
