plugins:
  - jekyll-feed
  - jekyll-favicon

exclude:
  - "Dockerfile"
  - "docker-compose.yml"

collections:
  tags:
    output: true
    permalink: tag/:title/

name: "Apollo Tech Corner"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /news/:categories/:title:output_ext
  - scope:
      path: ""
      type: tags
    values:
      layout: tag
  - scope:
      path: ""
    values:
      layout: "default"

feed:
  posts_limit: 1000
