theme: jekyll-theme-dinky

plugins:
  - jekyll-feed

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title:output_ext
  - scope:
      path: ""
    values:
      layout: "default"
