name: Jekyll CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4.1.0

      - name: Build Docker container
        run: docker compose build

      - name: Run Docker container
        run: docker compose up

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

